
# ------------------------------------------
# Configuration de Ruff
# ------------------------------------------

[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = [
	"F",   # erreurs (imports inutilisés, etc.)
	"I",   # tri des imports
	"UP",  # modernisation + future annotations
	"ANN",  # annotations de types
	"D",   # docstrings
]

ignore = [
	"ANN401", # Any implicite
	"D401", # impératif dans les docstrings
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "ANN"]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = false



# ------------------------------------------
# Configuration de Pyright
# ------------------------------------------

[tool.pyright]
include = ["src"]
exclude = ["tests"]
ignore = ["tests"]

typeCheckingMode = "basic"
reportOptionalReturn = "error"

executionEnvironments = [
	{ root = "src" }
]

# ------------------------------------------
# Configuration de Pytest
# ------------------------------------------

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = ["--import-mode=importlib"]