[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = [
  "F",   # erreurs (imports inutilisés, etc.)
  "I",   # tri des imports
  "UP",  # modernisation + future annotations
  "ANN",  # annotations de types
  "D",   # docstrings
]

ignore = [
  "ANN401", # Any implicite
  "D401", # impératif dans les docstrings
]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = false


# [tool.pyright]
# typeCheckingMode = "basic"
# reportOptionalReturn = "error"